# FindOpenCL.cmake — Android NDK override
#
# Placed in android/app/src/main/cpp/ and prepended to CMAKE_MODULE_PATH so that
# CMake finds THIS file before its built-in FindOpenCL.cmake when any subdirectory
# (including llama.cpp/ggml/src/ggml-opencl/) calls find_package(OpenCL [REQUIRED]).
#
# Why a custom finder?
#   The NDK sysroot does not ship libOpenCL.so — it is a vendor library present
#   only on the device (/vendor/lib64/libOpenCL.so on Mali devices like the M31).
#   CMake's built-in FindOpenCL.cmake calls find_library(OpenCL_LIBRARY OpenCL)
#   which searches the NDK sysroot and fails with OpenCL_FOUND=FALSE, aborting the
#   build even though the library WILL be present on the device.
#
# This file satisfies find_package(OpenCL REQUIRED) for Android by:
#   1. Using the Khronos OpenCL headers vendored at
#      android/app/src/main/cpp/opencl-headers/  (downloaded from KhronosGroup/OpenCL-Headers)
#   2. Creating an INTERFACE target OpenCL::OpenCL that points to a link-time stub
#      libOpenCL.so that exports all standard OpenCL API symbols as empty stubs.
#      The stub is excluded from the APK — the real Mali vendor libOpenCL.so is
#      used at runtime.
#
# On non-Android hosts the standard CMake FindOpenCL.cmake is used as normal.

if(ANDROID)
    # ── Headers ────────────────────────────────────────────────────────────────
    get_filename_component(_OCL_SELF_DIR "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY)
    set(_OCL_INCLUDE_DIR "${_OCL_SELF_DIR}/opencl-headers")

    if(NOT EXISTS "${_OCL_INCLUDE_DIR}/CL/cl.h")
        message(FATAL_ERROR
            "OpenCL headers not found at ${_OCL_INCLUDE_DIR}/CL/cl.h\n"
            "Run from android/app/src/main/cpp/:\n"
            "  git clone --depth 1 https://github.com/KhronosGroup/OpenCL-Headers opencl-headers\n"
            "Then rebuild.")
    endif()

    # ── Link-time stub libOpenCL.so ─────────────────────────────────────────────
    # The NDK sysroot does NOT ship libOpenCL.so — it is a vendor library present
    # only on the device (/vendor/lib64/libOpenCL.so on Mali devices like the M31).
    # lld with --no-undefined (set by the NDK toolchain for all shared libraries)
    # requires every symbol referenced by libggml-opencl.so to be resolvable at
    # link time, either from another .so or from this stub.
    #
    # The stub must export ALL OpenCL C API symbols that ggml-opencl.cpp references.
    # A one-function stub is not sufficient — the linker will emit "undefined symbol"
    # errors for each cl* function the code calls.
    #
    # The stub is compiled as a shared library named libOpenCL.so using the same NDK
    # cross-toolchain, satisfying lld at build time. It is then EXCLUDED from the APK
    # (see packagingOptions in build.gradle) so that at runtime the device's real
    # Mali vendor libOpenCL.so is used instead.
    if(NOT TARGET OpenCLStub)
        set(_OCL_STUB_SRC "${CMAKE_BINARY_DIR}/opencl_stub.c")
        file(WRITE "${_OCL_STUB_SRC}"
"/* OpenCL link-time stub for Android NDK builds.\n"
" * Provides empty implementations of all standard OpenCL C API functions.\n"
" * This library is excluded from the APK; the Mali vendor libOpenCL.so is\n"
" * loaded at runtime instead.\n"
" *\n"
" * Every cl* symbol that ggml-opencl.cpp references must appear here so that\n"
" * lld (--no-undefined) is satisfied at link time.\n"
" */\n"
"#define CL_TARGET_OPENCL_VERSION 300\n"
"#include <CL/cl.h>\n"
"\n"
"/* ---- Platform ---------------------------------------------------------- */\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetPlatformIDs(cl_uint n, cl_platform_id* p, cl_uint* np)\n"
"{ (void)n; (void)p; (void)np; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetPlatformInfo(cl_platform_id p, cl_platform_info i, size_t s, void* v, size_t* sr)\n"
"{ (void)p;(void)i;(void)s;(void)v;(void)sr; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY void* CL_API_CALL\n"
"clGetExtensionFunctionAddressForPlatform(cl_platform_id p, const char* n)\n"
"{ (void)p;(void)n; return (void*)0; }\n"
"\n"
"/* ---- Device ------------------------------------------------------------ */\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetDeviceIDs(cl_platform_id p, cl_device_type t, cl_uint n, cl_device_id* d, cl_uint* nd)\n"
"{ (void)p;(void)t;(void)n;(void)d;(void)nd; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetDeviceInfo(cl_device_id d, cl_device_info i, size_t s, void* v, size_t* sr)\n"
"{ (void)d;(void)i;(void)s;(void)v;(void)sr; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clCreateSubDevices(cl_device_id d, const cl_device_partition_property* p, cl_uint n, cl_device_id* od, cl_uint* nd)\n"
"{ (void)d;(void)p;(void)n;(void)od;(void)nd; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clRetainDevice(cl_device_id d) { (void)d; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clReleaseDevice(cl_device_id d) { (void)d; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clSetDefaultDeviceCommandQueue(cl_context c, cl_device_id d, cl_command_queue q)\n"
"{ (void)c;(void)d;(void)q; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetDeviceAndHostTimer(cl_device_id d, cl_ulong* dt, cl_ulong* ht)\n"
"{ (void)d;(void)dt;(void)ht; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetHostTimer(cl_device_id d, cl_ulong* ht)\n"
"{ (void)d;(void)ht; return CL_SUCCESS; }\n"
"\n"
"/* ---- Context ----------------------------------------------------------- */\n"
"CL_API_ENTRY cl_context CL_API_CALL\n"
"clCreateContext(const cl_context_properties* p, cl_uint n, const cl_device_id* d,\n"
"    void (CL_CALLBACK* f)(const char*, const void*, size_t, void*), void* u, cl_int* e)\n"
"{ (void)p;(void)n;(void)d;(void)f;(void)u; if(e)*e=CL_SUCCESS; return (cl_context)0; }\n"
"\n"
"CL_API_ENTRY cl_context CL_API_CALL\n"
"clCreateContextFromType(const cl_context_properties* p, cl_device_type t,\n"
"    void (CL_CALLBACK* f)(const char*, const void*, size_t, void*), void* u, cl_int* e)\n"
"{ (void)p;(void)t;(void)f;(void)u; if(e)*e=CL_SUCCESS; return (cl_context)0; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clRetainContext(cl_context c) { (void)c; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clReleaseContext(cl_context c) { (void)c; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetContextInfo(cl_context c, cl_context_info i, size_t s, void* v, size_t* sr)\n"
"{ (void)c;(void)i;(void)s;(void)v;(void)sr; return CL_SUCCESS; }\n"
"\n"
"/* ---- Command Queue ----------------------------------------------------- */\n"
"CL_API_ENTRY cl_command_queue CL_API_CALL\n"
"clCreateCommandQueueWithProperties(cl_context c, cl_device_id d,\n"
"    const cl_queue_properties* p, cl_int* e)\n"
"{ (void)c;(void)d;(void)p; if(e)*e=CL_SUCCESS; return (cl_command_queue)0; }\n"
"\n"
"CL_API_ENTRY cl_command_queue CL_API_CALL\n"
"clCreateCommandQueue(cl_context c, cl_device_id d, cl_command_queue_properties p, cl_int* e)\n"
"{ (void)c;(void)d;(void)p; if(e)*e=CL_SUCCESS; return (cl_command_queue)0; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clRetainCommandQueue(cl_command_queue q) { (void)q; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clReleaseCommandQueue(cl_command_queue q) { (void)q; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetCommandQueueInfo(cl_command_queue q, cl_command_queue_info i, size_t s, void* v, size_t* sr)\n"
"{ (void)q;(void)i;(void)s;(void)v;(void)sr; return CL_SUCCESS; }\n"
"\n"
"/* ---- Memory Objects ---------------------------------------------------- */\n"
"CL_API_ENTRY cl_mem CL_API_CALL\n"
"clCreateBuffer(cl_context c, cl_mem_flags f, size_t s, void* h, cl_int* e)\n"
"{ (void)c;(void)f;(void)s;(void)h; if(e)*e=CL_SUCCESS; return (cl_mem)0; }\n"
"\n"
"CL_API_ENTRY cl_mem CL_API_CALL\n"
"clCreateSubBuffer(cl_mem b, cl_mem_flags f, cl_buffer_create_type t, const void* i, cl_int* e)\n"
"{ (void)b;(void)f;(void)t;(void)i; if(e)*e=CL_SUCCESS; return (cl_mem)0; }\n"
"\n"
"CL_API_ENTRY cl_mem CL_API_CALL\n"
"clCreateImage(cl_context c, cl_mem_flags f, const cl_image_format* fmt,\n"
"    const cl_image_desc* d, void* h, cl_int* e)\n"
"{ (void)c;(void)f;(void)fmt;(void)d;(void)h; if(e)*e=CL_SUCCESS; return (cl_mem)0; }\n"
"\n"
"CL_API_ENTRY cl_mem CL_API_CALL\n"
"clCreatePipe(cl_context c, cl_mem_flags f, cl_uint ps, cl_uint ms,\n"
"    const cl_pipe_properties* p, cl_int* e)\n"
"{ (void)c;(void)f;(void)ps;(void)ms;(void)p; if(e)*e=CL_SUCCESS; return (cl_mem)0; }\n"
"\n"
"CL_API_ENTRY cl_mem CL_API_CALL\n"
"clCreateBufferWithProperties(cl_context c, const cl_mem_properties* p,\n"
"    cl_mem_flags f, size_t s, void* h, cl_int* e)\n"
"{ (void)c;(void)p;(void)f;(void)s;(void)h; if(e)*e=CL_SUCCESS; return (cl_mem)0; }\n"
"\n"
"CL_API_ENTRY cl_mem CL_API_CALL\n"
"clCreateImageWithProperties(cl_context c, const cl_mem_properties* p,\n"
"    cl_mem_flags f, const cl_image_format* fmt, const cl_image_desc* d, void* h, cl_int* e)\n"
"{ (void)c;(void)p;(void)f;(void)fmt;(void)d;(void)h; if(e)*e=CL_SUCCESS; return (cl_mem)0; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clRetainMemObject(cl_mem m) { (void)m; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clReleaseMemObject(cl_mem m) { (void)m; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetSupportedImageFormats(cl_context c, cl_mem_flags f, cl_mem_object_type t,\n"
"    cl_uint n, cl_image_format* fmts, cl_uint* nf)\n"
"{ (void)c;(void)f;(void)t;(void)n;(void)fmts;(void)nf; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetMemObjectInfo(cl_mem m, cl_mem_info i, size_t s, void* v, size_t* sr)\n"
"{ (void)m;(void)i;(void)s;(void)v;(void)sr; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetImageInfo(cl_mem i, cl_image_info ii, size_t s, void* v, size_t* sr)\n"
"{ (void)i;(void)ii;(void)s;(void)v;(void)sr; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetPipeInfo(cl_mem p, cl_pipe_info i, size_t s, void* v, size_t* sr)\n"
"{ (void)p;(void)i;(void)s;(void)v;(void)sr; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clSetMemObjectDestructorCallback(cl_mem m,\n"
"    void (CL_CALLBACK* f)(cl_mem, void*), void* u)\n"
"{ (void)m;(void)f;(void)u; return CL_SUCCESS; }\n"
"\n"
"/* ---- SVM --------------------------------------------------------------- */\n"
"CL_API_ENTRY void* CL_API_CALL\n"
"clSVMAlloc(cl_context c, cl_svm_mem_flags f, size_t s, cl_uint a)\n"
"{ (void)c;(void)f;(void)s;(void)a; return (void*)0; }\n"
"\n"
"CL_API_ENTRY void CL_API_CALL\n"
"clSVMFree(cl_context c, void* p) { (void)c;(void)p; }\n"
"\n"
"/* ---- Sampler ----------------------------------------------------------- */\n"
"CL_API_ENTRY cl_sampler CL_API_CALL\n"
"clCreateSamplerWithProperties(cl_context c, const cl_sampler_properties* p, cl_int* e)\n"
"{ (void)c;(void)p; if(e)*e=CL_SUCCESS; return (cl_sampler)0; }\n"
"\n"
"CL_API_ENTRY cl_sampler CL_API_CALL\n"
"clCreateSampler(cl_context c, cl_bool nm, cl_addressing_mode am, cl_filter_mode fm, cl_int* e)\n"
"{ (void)c;(void)nm;(void)am;(void)fm; if(e)*e=CL_SUCCESS; return (cl_sampler)0; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clRetainSampler(cl_sampler s) { (void)s; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clReleaseSampler(cl_sampler s) { (void)s; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetSamplerInfo(cl_sampler s, cl_sampler_info i, size_t sz, void* v, size_t* sr)\n"
"{ (void)s;(void)i;(void)sz;(void)v;(void)sr; return CL_SUCCESS; }\n"
"\n"
"/* ---- Program ----------------------------------------------------------- */\n"
"CL_API_ENTRY cl_program CL_API_CALL\n"
"clCreateProgramWithSource(cl_context c, cl_uint n, const char** s, const size_t* l, cl_int* e)\n"
"{ (void)c;(void)n;(void)s;(void)l; if(e)*e=CL_SUCCESS; return (cl_program)0; }\n"
"\n"
"CL_API_ENTRY cl_program CL_API_CALL\n"
"clCreateProgramWithBinary(cl_context c, cl_uint n, const cl_device_id* d,\n"
"    const size_t* l, const unsigned char** b, cl_int* bs, cl_int* e)\n"
"{ (void)c;(void)n;(void)d;(void)l;(void)b;(void)bs; if(e)*e=CL_SUCCESS; return (cl_program)0; }\n"
"\n"
"CL_API_ENTRY cl_program CL_API_CALL\n"
"clCreateProgramWithBuiltInKernels(cl_context c, cl_uint n, const cl_device_id* d,\n"
"    const char* k, cl_int* e)\n"
"{ (void)c;(void)n;(void)d;(void)k; if(e)*e=CL_SUCCESS; return (cl_program)0; }\n"
"\n"
"CL_API_ENTRY cl_program CL_API_CALL\n"
"clCreateProgramWithIL(cl_context c, const void* il, size_t l, cl_int* e)\n"
"{ (void)c;(void)il;(void)l; if(e)*e=CL_SUCCESS; return (cl_program)0; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clRetainProgram(cl_program p) { (void)p; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clReleaseProgram(cl_program p) { (void)p; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clBuildProgram(cl_program p, cl_uint n, const cl_device_id* d, const char* opts,\n"
"    void (CL_CALLBACK* f)(cl_program, void*), void* u)\n"
"{ (void)p;(void)n;(void)d;(void)opts;(void)f;(void)u; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clCompileProgram(cl_program p, cl_uint n, const cl_device_id* d, const char* opts,\n"
"    cl_uint ni, const cl_program* hp, const char** hn,\n"
"    void (CL_CALLBACK* f)(cl_program, void*), void* u)\n"
"{ (void)p;(void)n;(void)d;(void)opts;(void)ni;(void)hp;(void)hn;(void)f;(void)u; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_program CL_API_CALL\n"
"clLinkProgram(cl_context c, cl_uint n, const cl_device_id* d, const char* opts,\n"
"    cl_uint ni, const cl_program* ip,\n"
"    void (CL_CALLBACK* f)(cl_program, void*), void* u, cl_int* e)\n"
"{ (void)c;(void)n;(void)d;(void)opts;(void)ni;(void)ip;(void)f;(void)u; if(e)*e=CL_SUCCESS; return (cl_program)0; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clSetProgramReleaseCallback(cl_program p,\n"
"    void (CL_CALLBACK* f)(cl_program, void*), void* u)\n"
"{ (void)p;(void)f;(void)u; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clSetProgramSpecializationConstant(cl_program p, cl_uint i, size_t s, const void* v)\n"
"{ (void)p;(void)i;(void)s;(void)v; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clUnloadPlatformCompiler(cl_platform_id p) { (void)p; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetProgramInfo(cl_program p, cl_program_info i, size_t s, void* v, size_t* sr)\n"
"{ (void)p;(void)i;(void)s;(void)v;(void)sr; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetProgramBuildInfo(cl_program p, cl_device_id d, cl_program_build_info i, size_t s, void* v, size_t* sr)\n"
"{ (void)p;(void)d;(void)i;(void)s;(void)v;(void)sr; return CL_SUCCESS; }\n"
"\n"
"/* ---- Kernel ------------------------------------------------------------ */\n"
"CL_API_ENTRY cl_kernel CL_API_CALL\n"
"clCreateKernel(cl_program p, const char* n, cl_int* e)\n"
"{ (void)p;(void)n; if(e)*e=CL_SUCCESS; return (cl_kernel)0; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clCreateKernelsInProgram(cl_program p, cl_uint n, cl_kernel* k, cl_uint* nk)\n"
"{ (void)p;(void)n;(void)k;(void)nk; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_kernel CL_API_CALL\n"
"clCloneKernel(cl_kernel k, cl_int* e)\n"
"{ (void)k; if(e)*e=CL_SUCCESS; return (cl_kernel)0; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clRetainKernel(cl_kernel k) { (void)k; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clReleaseKernel(cl_kernel k) { (void)k; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clSetKernelArg(cl_kernel k, cl_uint i, size_t s, const void* v)\n"
"{ (void)k;(void)i;(void)s;(void)v; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clSetKernelArgSVMPointer(cl_kernel k, cl_uint i, const void* p)\n"
"{ (void)k;(void)i;(void)p; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clSetKernelExecInfo(cl_kernel k, cl_kernel_exec_info n, size_t s, const void* v)\n"
"{ (void)k;(void)n;(void)s;(void)v; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetKernelInfo(cl_kernel k, cl_kernel_info i, size_t s, void* v, size_t* sr)\n"
"{ (void)k;(void)i;(void)s;(void)v;(void)sr; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetKernelArgInfo(cl_kernel k, cl_uint ai, cl_kernel_arg_info i, size_t s, void* v, size_t* sr)\n"
"{ (void)k;(void)ai;(void)i;(void)s;(void)v;(void)sr; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetKernelWorkGroupInfo(cl_kernel k, cl_device_id d, cl_kernel_work_group_info i, size_t s, void* v, size_t* sr)\n"
"{ (void)k;(void)d;(void)i;(void)s;(void)v;(void)sr; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetKernelSubGroupInfo(cl_kernel k, cl_device_id d, cl_kernel_sub_group_info i,\n"
"    size_t is, const void* iv, size_t s, void* v, size_t* sr)\n"
"{ (void)k;(void)d;(void)i;(void)is;(void)iv;(void)s;(void)v;(void)sr; return CL_SUCCESS; }\n"
"\n"
"/* ---- Events ------------------------------------------------------------ */\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clWaitForEvents(cl_uint n, const cl_event* e)\n"
"{ (void)n;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetEventInfo(cl_event e, cl_event_info i, size_t s, void* v, size_t* sr)\n"
"{ (void)e;(void)i;(void)s;(void)v;(void)sr; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_event CL_API_CALL\n"
"clCreateUserEvent(cl_context c, cl_int* e)\n"
"{ (void)c; if(e)*e=CL_SUCCESS; return (cl_event)0; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clRetainEvent(cl_event e) { (void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clReleaseEvent(cl_event e) { (void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clSetUserEventStatus(cl_event e, cl_int s) { (void)e;(void)s; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clSetEventCallback(cl_event e, cl_int t, void (CL_CALLBACK* f)(cl_event,cl_int,void*), void* u)\n"
"{ (void)e;(void)t;(void)f;(void)u; return CL_SUCCESS; }\n"
"\n"
"/* ---- Profiling --------------------------------------------------------- */\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clGetEventProfilingInfo(cl_event e, cl_profiling_info i, size_t s, void* v, size_t* sr)\n"
"{ (void)e;(void)i;(void)s;(void)v;(void)sr; return CL_SUCCESS; }\n"
"\n"
"/* ---- Flush / Finish ---------------------------------------------------- */\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clFlush(cl_command_queue q) { (void)q; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clFinish(cl_command_queue q) { (void)q; return CL_SUCCESS; }\n"
"\n"
"/* ---- Enqueue Buffer ---------------------------------------------------- */\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueReadBuffer(cl_command_queue q, cl_mem b, cl_bool bl, size_t o, size_t s,\n"
"    void* p, cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)b;(void)bl;(void)o;(void)s;(void)p;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueReadBufferRect(cl_command_queue q, cl_mem b, cl_bool bl,\n"
"    const size_t* bo, const size_t* ho, const size_t* r,\n"
"    size_t brp, size_t bsp, size_t hrp, size_t hsp,\n"
"    void* p, cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)b;(void)bl;(void)bo;(void)ho;(void)r;\n"
"  (void)brp;(void)bsp;(void)hrp;(void)hsp;(void)p;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueWriteBuffer(cl_command_queue q, cl_mem b, cl_bool bl, size_t o, size_t s,\n"
"    const void* p, cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)b;(void)bl;(void)o;(void)s;(void)p;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueWriteBufferRect(cl_command_queue q, cl_mem b, cl_bool bl,\n"
"    const size_t* bo, const size_t* ho, const size_t* r,\n"
"    size_t brp, size_t bsp, size_t hrp, size_t hsp,\n"
"    const void* p, cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)b;(void)bl;(void)bo;(void)ho;(void)r;\n"
"  (void)brp;(void)bsp;(void)hrp;(void)hsp;(void)p;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueFillBuffer(cl_command_queue q, cl_mem b, const void* p, size_t ps,\n"
"    size_t o, size_t s, cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)b;(void)p;(void)ps;(void)o;(void)s;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueCopyBuffer(cl_command_queue q, cl_mem s, cl_mem d,\n"
"    size_t so, size_t do_, size_t sz, cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)s;(void)d;(void)so;(void)do_;(void)sz;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueCopyBufferRect(cl_command_queue q, cl_mem s, cl_mem d,\n"
"    const size_t* so, const size_t* do_, const size_t* r,\n"
"    size_t srp, size_t ssp, size_t drp, size_t dsp,\n"
"    cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)s;(void)d;(void)so;(void)do_;(void)r;\n"
"  (void)srp;(void)ssp;(void)drp;(void)dsp;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"/* ---- Enqueue Image ----------------------------------------------------- */\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueReadImage(cl_command_queue q, cl_mem im, cl_bool bl,\n"
"    const size_t* o, const size_t* r, size_t rp, size_t sp,\n"
"    void* p, cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)im;(void)bl;(void)o;(void)r;(void)rp;(void)sp;(void)p;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueWriteImage(cl_command_queue q, cl_mem im, cl_bool bl,\n"
"    const size_t* o, const size_t* r, size_t rp, size_t sp,\n"
"    const void* p, cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)im;(void)bl;(void)o;(void)r;(void)rp;(void)sp;(void)p;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueFillImage(cl_command_queue q, cl_mem im, const void* fc,\n"
"    const size_t* o, const size_t* r, cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)im;(void)fc;(void)o;(void)r;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueCopyImage(cl_command_queue q, cl_mem si, cl_mem di,\n"
"    const size_t* so, const size_t* do_, const size_t* r,\n"
"    cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)si;(void)di;(void)so;(void)do_;(void)r;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueCopyImageToBuffer(cl_command_queue q, cl_mem si, cl_mem db,\n"
"    const size_t* so, const size_t* r, size_t dbo,\n"
"    cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)si;(void)db;(void)so;(void)r;(void)dbo;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueCopyBufferToImage(cl_command_queue q, cl_mem sb, cl_mem di,\n"
"    size_t sbo, const size_t* do_, const size_t* r,\n"
"    cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)sb;(void)di;(void)sbo;(void)do_;(void)r;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"/* ---- Enqueue Map/Unmap ------------------------------------------------- */\n"
"CL_API_ENTRY void* CL_API_CALL\n"
"clEnqueueMapBuffer(cl_command_queue q, cl_mem b, cl_bool bl, cl_map_flags f,\n"
"    size_t o, size_t s, cl_uint nw, const cl_event* wl, cl_event* e, cl_int* err)\n"
"{ (void)q;(void)b;(void)bl;(void)f;(void)o;(void)s;(void)nw;(void)wl;(void)e;\n"
"  if(err)*err=CL_SUCCESS; return (void*)0; }\n"
"\n"
"CL_API_ENTRY void* CL_API_CALL\n"
"clEnqueueMapImage(cl_command_queue q, cl_mem im, cl_bool bl, cl_map_flags f,\n"
"    const size_t* o, const size_t* r, size_t* rp, size_t* sp,\n"
"    cl_uint nw, const cl_event* wl, cl_event* e, cl_int* err)\n"
"{ (void)q;(void)im;(void)bl;(void)f;(void)o;(void)r;(void)rp;(void)sp;\n"
"  (void)nw;(void)wl;(void)e; if(err)*err=CL_SUCCESS; return (void*)0; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueUnmapMemObject(cl_command_queue q, cl_mem m, void* p,\n"
"    cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)m;(void)p;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueMigrateMemObjects(cl_command_queue q, cl_uint n, const cl_mem* m,\n"
"    cl_mem_migration_flags f, cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)n;(void)m;(void)f;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"/* ---- Enqueue Kernel ---------------------------------------------------- */\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueNDRangeKernel(cl_command_queue q, cl_kernel k, cl_uint wd,\n"
"    const size_t* go, const size_t* gws, const size_t* lws,\n"
"    cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)k;(void)wd;(void)go;(void)gws;(void)lws;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueNativeKernel(cl_command_queue q,\n"
"    void (CL_CALLBACK* f)(void*), void* a, size_t as,\n"
"    cl_uint nm, const cl_mem* ml, const void** al,\n"
"    cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)f;(void)a;(void)as;(void)nm;(void)ml;(void)al;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"/* ---- Enqueue Marker / Barrier ------------------------------------------ */\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueMarkerWithWaitList(cl_command_queue q, cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueBarrierWithWaitList(cl_command_queue q, cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"/* ---- Enqueue SVM ------------------------------------------------------- */\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueSVMFree(cl_command_queue q, cl_uint n, void* p[],\n"
"    void (CL_CALLBACK* f)(cl_command_queue, cl_uint, void*[], void*), void* u,\n"
"    cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)n;(void)p;(void)f;(void)u;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueSVMMemcpy(cl_command_queue q, cl_bool bl, void* d, const void* s, size_t sz,\n"
"    cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)bl;(void)d;(void)s;(void)sz;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueSVMMemFill(cl_command_queue q, void* p, const void* pat, size_t ps, size_t s,\n"
"    cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)p;(void)pat;(void)ps;(void)s;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueSVMMap(cl_command_queue q, cl_bool bl, cl_map_flags f, void* p, size_t s,\n"
"    cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)bl;(void)f;(void)p;(void)s;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueSVMUnmap(cl_command_queue q, void* p, cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)p;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
"\n"
"CL_API_ENTRY cl_int CL_API_CALL\n"
"clEnqueueSVMMigrateMem(cl_command_queue q, cl_uint n, const void** p, const size_t* s,\n"
"    cl_mem_migration_flags f, cl_uint nw, const cl_event* wl, cl_event* e)\n"
"{ (void)q;(void)n;(void)p;(void)s;(void)f;(void)nw;(void)wl;(void)e; return CL_SUCCESS; }\n"
)
        add_library(OpenCLStub SHARED "${_OCL_STUB_SRC}")
        target_include_directories(OpenCLStub PRIVATE "${_OCL_INCLUDE_DIR}")
        set_target_properties(OpenCLStub PROPERTIES
            OUTPUT_NAME "OpenCL"
            LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/opencl_stub_dir"
        )
    endif()

    # ── INTERFACE target ────────────────────────────────────────────────────────
    # OpenCL::OpenCL is the canonical modern CMake target — ggml-opencl links against it.
    if(NOT TARGET OpenCL::OpenCL)
        add_library(OpenCL::OpenCL INTERFACE IMPORTED GLOBAL)
        target_include_directories(OpenCL::OpenCL INTERFACE "${_OCL_INCLUDE_DIR}")
        # Link against the stub target (full path). CMake resolves this to the
        # actual libOpenCL.so binary so lld never sees a bare "-lOpenCL".
        # The resulting libggml-opencl.so records DT_NEEDED: libOpenCL.so and the
        # device dynamic linker satisfies this from the vendor partition at runtime.
        target_link_libraries(OpenCL::OpenCL INTERFACE OpenCLStub)
    endif()

    # ── Variables expected by FindOpenCL consumers ──────────────────────────────
    set(OpenCL_FOUND        TRUE)
    set(OpenCL_INCLUDE_DIRS "${_OCL_INCLUDE_DIR}")
    set(OpenCL_INCLUDE_DIR  "${_OCL_INCLUDE_DIR}")
    set(OpenCL_LIBRARIES    OpenCL::OpenCL)
    set(OpenCL_LIBRARY      OpenCL::OpenCL)
    set(OpenCL_VERSION_STRING  "2.0")
    set(OpenCL_VERSION_MAJOR   2)
    set(OpenCL_VERSION_MINOR   0)

    mark_as_advanced(OpenCL_INCLUDE_DIR OpenCL_LIBRARY)

    message(STATUS "ARIA FindOpenCL: Android — vendored Khronos headers + comprehensive link-time stub libOpenCL.so (runtime: Mali vendor driver)")

else()
    # ── Non-Android: delegate to CMake's built-in FindOpenCL.cmake ─────────────
    # Temporarily remove ourselves from MODULE_PATH to avoid infinite recursion,
    # then restore after the built-in finder runs.
    list(REMOVE_ITEM CMAKE_MODULE_PATH "${_OCL_SELF_DIR}")

    # Pass through REQUIRED / QUIET so the caller's intent is respected
    if(OpenCL_FIND_REQUIRED AND OpenCL_FIND_QUIETLY)
        find_package(OpenCL REQUIRED QUIET)
    elseif(OpenCL_FIND_REQUIRED)
        find_package(OpenCL REQUIRED)
    elseif(OpenCL_FIND_QUIETLY)
        find_package(OpenCL QUIET)
    else()
        find_package(OpenCL)
    endif()

    list(PREPEND CMAKE_MODULE_PATH "${_OCL_SELF_DIR}")
endif()
