package expo.modules

/**
 * ExpoModulesPackageList — native-only stub.
 *
 * In hybrid mode (rnEnabled = true, node_modules present), this file is
 * auto-generated by expo-module-gradle-plugin and lists all Expo native
 * modules that Gradle discovered via autolinking.
 *
 * In native-only mode (Firebase Studio / Android Studio without node_modules),
 * Expo jars are not on the classpath. This stub keeps the package declaration
 * so the source set compiles cleanly. The class is intentionally absent —
 * nothing in the pure Kotlin build references ExpoModulesPackageList.
 *
 * Phase 8 (migration.md): delete this file once the RN/Expo layer is removed.
 */
